name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
  - name: BUILD_VERSION
    value: '0.1.1'
  - group: NuGet.org

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.4.x'
  inputs:
    versionSpec: 5.4.x

- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1.x'
  inputs:
    packageType: sdk
    version: 3.1.x

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: Blobucket.sln
    arguments: -c Release

- task: DotNetCoreCLI@2
  displayName: Unit Tests
  inputs:
    command: test
    arguments: '-c Release --no-build /p:CollectCoverage=true'

- pwsh: |
    Get-ChildItem -Path *.nupkg -Recurse -Exclude *.symbols.nupkg | ForEach-Object {
      Write-Host "##[command]dotnet nuget push '$($_.FullName)' --source https://api.nuget.org/v3/index.json --api-key *** --skip-duplicate"
      dotnet nuget push $_.FullName --source https://api.nuget.org/v3/index.json --api-key $(nuget.org-blobucket) --skip-duplicate
    }
  displayName: NuGet Push