name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
  BUILD_VERSION: '0.1.0'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.4.x'
  inputs:
    versionSpec: 5.4.x

- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1.x'
  inputs:
    packageType: sdk
    version: 3.1.x

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: Blobucket.sln
    arguments: -c Release

- task: DotNetCoreCLI@2
  displayName: Unit Tests
  inputs:
    command: test
    arguments: -c Release --no-build

- task: NuGetCommand@2
  displayName: NuGet Push
  #condition: eq(variables['Build.SourceBranchName'], 'master')
  inputs:
    command: push
    packagesToPush: '**/*.nupkg;!**/*.symbols.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'nuget.org_blobucket'
    allowPackageConflicts: true